/** *****************************************************************************
 * JMMC project ( http://www.jmmc.fr ) - Copyright (C) CNRS.
 ***************************************************************************** */
package fr.jmmc.oimaging.gui;

import fr.jmmc.jmcs.App;
import fr.jmmc.jmcs.gui.component.ComponentResizeAdapter;
import fr.jmmc.jmcs.gui.util.WindowUtils;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * Panel to be added in a dialog box to edit the display of the table
 *
 * @author martin
 */
public class TableEditorPanel extends javax.swing.JPanel {

    /** default serial UID for Serializable interface */
    private static final long serialVersionUID = 1;

    /**
     * Display the table editor using the given target name as the initial selected target
     * @param allColumns All available columns (currently displayed or not) 
     * @param displayedColumns Currently displayed columns
     * @param dialogSizePref optional preference key to restore dialog size
     * @return updated visible column names or null
     */
    public static List<String> showEditor(final List<String> allColumns,
                                          final List<String> displayedColumns,
                                          final String dialogSizePref) {

        // 1. Create the dialog (modal):
        final JDialog dialog = new JDialog(App.getFrame(), "Edit table columns", true);

        final Dimension dim = new Dimension(600, 500);
        dialog.setMinimumSize(dim);
        dialog.addComponentListener(new ComponentResizeAdapter(dim));

        // 2. Optional: What happens when the dialog closes ?
        dialog.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // 3. Create components and put them in the dialog
        final TableEditorPanel tableEditorPanel = new TableEditorPanel(dialog, allColumns, displayedColumns);
        dialog.add(tableEditorPanel);

        // 4. Size the dialog.
        WindowUtils.setClosingKeyboardShortcuts(dialog);
        dialog.pack();

        // Restore, then automatically save window size changes:
        WindowUtils.rememberWindowSize(dialog, dialogSizePref);

        // Center it :
        dialog.setLocationRelativeTo(dialog.getOwner());

        // 5. Show it and waits until dialog is not visible or disposed :
        dialog.setResizable(true);
        dialog.setVisible(true);

        // when dialog returns OK, set the chosen columns
        if (tableEditorPanel.isResult()) {
            return tableEditorPanel.getVisibleColumns();
        }
        return null;
    }

    /* members */
    // Model and view for the list
    private final DefaultListModel<String> modelHidden = new DefaultListModel<>();
    private final DefaultListModel<String> modelDisplayed = new DefaultListModel<>();

    // Reference to the parent dialog box to handle its events
    private final JDialog dialog;

    /** editor result = true if the user validates the inputs */
    private boolean result = false;
    /** list of all columns (used by reset) */
    private final List<String> allColumns;

    /**
     * Constructor
     * @param dialog Reference to the parent dialog box to handle its events
     * @param allColumns All available columns (currently displayed or not) 
     * @param displayedColumns Currently displayed columns
     */
    private TableEditorPanel(final JDialog dialog, final List<String> allColumns, final List<String> displayedColumns) {
        initComponents();
        this.dialog = dialog;
        this.allColumns = allColumns;

        // Fill with available columns, but remove the ones already displayed
        allColumns.forEach(modelHidden::addElement);
        displayedColumns.forEach(modelHidden::removeElement);

        displayedColumns.forEach(modelDisplayed::addElement);

        jListHidden.setModel(modelHidden);
        jListDisplayed.setModel(modelDisplayed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonAdd = new javax.swing.JButton();
        jLabelDisplayed = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jLabelHidden = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jScrollPaneHidden = new javax.swing.JScrollPane();
        jListHidden = new javax.swing.JList<>();
        jScrollPaneDisplayed = new javax.swing.JScrollPane();
        jListDisplayed = new javax.swing.JList<>();
        jButtonReset = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(400, 250));
        setLayout(new java.awt.GridBagLayout());

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jButtonAdd, gridBagConstraints);

        jLabelDisplayed.setText("Displayed columns");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelDisplayed, gridBagConstraints);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jButtonOk, gridBagConstraints);

        jLabelHidden.setText("Hidden columns");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelHidden, gridBagConstraints);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jButtonCancel, gridBagConstraints);

        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jButtonRemove, gridBagConstraints);

        jListHidden.setToolTipText("");
        jScrollPaneHidden.setViewportView(jListHidden);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(jScrollPaneHidden, gridBagConstraints);

        jScrollPaneDisplayed.setViewportView(jListDisplayed);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(jScrollPaneDisplayed, gridBagConstraints);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jButtonReset, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        jListHidden.getSelectedValuesList().forEach(column -> {
            modelDisplayed.addElement(column);
            modelHidden.removeElement(column);
        });
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        jListDisplayed.getSelectedValuesList().forEach(column -> {
            modelHidden.addElement(column);
            modelDisplayed.removeElement(column);
        });
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        this.result = true;
        dialog.dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dialog.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        modelHidden.clear();
        modelDisplayed.clear();
        allColumns.forEach(modelDisplayed::addElement);
    }//GEN-LAST:event_jButtonResetActionPerformed

    protected List<String> getVisibleColumns() {
        final List<String> displayedColumns = new ArrayList<>(modelDisplayed.size());
        for (Enumeration<String> e = modelDisplayed.elements(); e.hasMoreElements();) {
            displayedColumns.add(e.nextElement());
        }
        return displayedColumns;
    }

    /**
     * Return the editor result
     * @return true if the user validated (ok button)
     */
    protected boolean isResult() {
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabelDisplayed;
    private javax.swing.JLabel jLabelHidden;
    private javax.swing.JList<String> jListDisplayed;
    private javax.swing.JList<String> jListHidden;
    private javax.swing.JScrollPane jScrollPaneDisplayed;
    private javax.swing.JScrollPane jScrollPaneHidden;
    // End of variables declaration//GEN-END:variables

}
